### ISSUE TITLE
Don't depend on SNAPSHOT versions

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#92] opened 2018-01-19 13:36 UTC
When using SNAPSHOT versions, the dependency is downloaded every time. this also happens for transitive dependencies, such as when compiling OTP.

**Comment by vinjana** [comment] 2018-01-19 13:38
What should be the alternative then during development? In the release version the commit/tag will be fixed.

**Comment by vinjana** [comment] 2018-01-19 13:39
This is not a bug but intended behavior ;-)

**Comment by askask** [comment] 2018-01-19 13:59
> In the release version the commit/tag will be fixed.
I didn't know that, that's ok for me

**Closed** 2018-02-12 10:52 UTC
Labels: bug
